# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c74ad2e3cec328e674ddce27345b86c317db75de93735fcb1d7cfb5ad4c364fc21ba67d682c06893ba1c55a83d329fccde412138c605e2ef1fc402641f83205

test:
  secret_key_base: 4e30e8ee069861679e53c2bc1b2a4e3e2f61a0228d6dd78b899970fb97a4b5da841d8dd600135fcefbb24e9d2af38cd471fbe080b09846744a82660f0976971c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
